### ISSUE TITLE
WordPress.org - nahrávání do repozitáře

### ISSUE THREAD

**Issue by kalich5** [skaut/crdm-spolky-zaklad#1]
Výsledek automatického skenu šablony: Neúspěšné
REQUIRED: This theme doesn't seem to display tags. Modify it to display tags in appropriate locations.
REQUIRED: .wp-caption css class is needed in your theme css.
REQUIRED: .wp-caption-text css class is needed in your theme css.
REQUIRED: .sticky css class is needed in your theme css.
REQUIRED: .screen-reader-text css class is needed in your theme css. See See: the Codex for an example implementation.
REQUIRED: .gallery-caption css class is needed in your theme css.
REQUIRED: .bypostauthor css class is needed in your theme css.
REQUIRED: .aligncenter css class is needed in your theme css.
RECOMMENDED: This theme contains no sidebars/widget areas. See Widgets API
Warning: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs.
The domains found are crdm_basic, kirki
WARNING: Could not find the file index.php in the theme.
REQUIRED: This theme doesn't seem to support the standard avatar functions. Use get_avatar or wp_list_comments to add this support.
REQUIRED: The theme must not used the <title> tags.
REQUIRED: The theme must not call to wp_title().
REQUIRED: The theme doesn't have post pagination code in it. Use posts_nav_link() or paginate_links() or the_posts_pagination() or the_posts_navigation() or next_posts_link() and previous_posts_link() to add post pagination.
REQUIRED: The theme doesn't have comment pagination code in it. Use paginate_comments_links() or the_comments_navigation or the_comments_pagination or next_comments_link() and previous_comments_link() to add comment pagination.
REQUIRED: No reference to add_theme_support( "title-tag" ) was found in the theme.
REQUIRED: No content width has been defined. Example:
if ( ! isset( $content_width ) ) $content_width = 900;
REQUIRED: Could not find the comment-reply script enqueued. See: Migrating Plugins and Themes to 2.7/Enhanced Comment Display
 <?php if ( is_singular() ) wp_enqueue_script( "comment-reply" ); ?>
REQUIRED: Could not find wp_list_comments. See: wp_list_comments
 <?php wp_list_comments( $args ); ?>
REQUIRED: Could not find wp_link_pages. See: wp_link_pages
 <?php wp_link_pages( $args ); ?>
REQUIRED: Could not find wp_head. See: wp_head
 <?php wp_head(); ?>
REQUIRED: Could not find wp_footer. See: wp_footer
 <?php wp_footer(); ?>
REQUIRED: Could not find post_class. See: post_class
 <div id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
REQUIRED: Could not find language_attributes. See: language_attributes
<html <?php language_attributes(); ?>
REQUIRED: Could not find comments_template. See: comments_template
 <?php comments_template( $file, $separate_comments ); ?>
REQUIRED: Could not find comment_form. See: comment_form
 <?php comment_form(); ?>
REQUIRED: Could not find body_class call in body tag. See: body_class
 <?php body_class( $class ); ?>
REQUIRED: Could not find add_theme_support( 'automatic-feed-links' ). See: add_theme_support
 <?php add_theme_support( $feature ); ?>
REQUIRED: Could not find DOCTYPE. See: https://codex.wordpress.org/HTML_to_XHTML
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"?>
RECOMMENDED: No reference to post-thumbnails was found in the theme. If the theme has a thumbnail like functionality, it should be implemented with add_theme_support( "post-thumbnails" )in the functions.php file.
RECOMMENDED: No reference to nav_menu's was found in the theme. Note that if your theme has a menu bar, it is required to use the WordPress nav_menu functionality for it.
RECOMMENDED: No reference to add_theme_support( "custom-header", $args ) was found in the theme. It is recommended that the theme implement this functionality if using an image for the header.
RECOMMENDED: No reference to add_theme_support( "custom-background", $args ) was found in the theme. If the theme uses background images or solid colors for the background, then it is recommended that the theme implement this functionality.
RECOMMENDED: No reference to add_editor_style() was found in the theme. It is recommended that the theme implement editor styling, so as to make the editor content match the resulting post output in the theme, for a better user experience.
RECOMMENDED: Could not find the file readme.txt in the theme. Please see Theme_Documentation for more information.
INFO: Non-printable characters were found in the functions.php file. You may want to check this file for errors.
Line 22: // if incompatible version of WP / PHP => don´t init
Line 76: Helpers::showAdminNotice( esc_html__( '��ablona ČRDM - základní vy��aduje verzi WordPress 4.9.6 nebo vy����í!'
Line 80: Helpers::showAdminNotice( esc_html__( '��ablona ČRDM - základní vy��aduje verzi PHP 7.0 nebo vy����í!', 'crdm_
INFO: Non-printable characters were found in the Sidebar.php file. You may want to check this file for errors.
Line 24: 'title' => esc_attr__( 'Postranní panely', 'crdm_basic' ),
Line 33: 'label'     => esc_attr__( 'Pozadí', 'crdm_basic' ),
Line 54: 'label'     => esc_attr__( 'Barva stínu boxu', 'crdm_basic' ),
Line 92: 'label'     => esc_attr__( 'Bě��ný text', 'crdm_basic' ),
Line 113: 'label'     => esc_attr__( 'Barva odkaz��', 'crdm_basic' ),
INFO: Non-printable characters were found in the PageHeader.php file. You may want to check this file for errors.
Line 24: 'title'       => esc_attr__( 'Hlavi��ka stránek', 'crdm_basic' ),
Line 25: 'description' => esc_attr__( 'Hlavi��ka s obrázkem, nadpisem a podnadpisem jednotlivých stránek', 'crdm_bas
Line 35: 'description' => esc_attr__( 'Barva pozadí boxu s textem', 'crdm_basic' ),
Line 57: 'description' => esc_attr__( 'Zadejte v��etn�� jednotky, např.: 50px, 10%, ...', 'crdm_basic' ),
INFO: Non-printable characters were found in the Menu.php file. You may want to check this file for errors.
Line 33: 'label'     => esc_attr__( 'Pozadí lišty', 'crdm_basic' ),
Line 54: 'label'     => esc_attr__( 'Položky menu', 'crdm_basic' ),
Line 81: 'label'     => esc_attr__( 'Barva odd��lova��e položek menu', 'crdm_basic' ),
Line 96: 'label'     => esc_attr__( 'Pozadí vysouvacího menu', 'crdm_basic' ),
Line 117: 'label'     => esc_attr__( 'Položky submenu', 'crdm_basic' ),
Line 139: 'label'     => esc_attr__( 'Barva odd��lova��e položek submenu', 'crdm_basic' ),
INFO: Non-printable characters were found in the Init.php file. You may want to check this file for errors.
Line 30: 'title' => esc_attr__( 'Nastaven�� šablony', 'crdm_basic' )
INFO: Non-printable characters were found in the Helpers.php file. You may want to check this file for errors.
Line 34: <span class='screen-reader-text'>' . __( 'Zav��ít', 'crdm_basic' ) . '</span>
INFO: Non-printable characters were found in the Footer.php file. You may want to check this file for errors.
Line 24: 'title' => esc_attr__( 'Patička', 'crdm_basic' ),
Line 33: 'label'     => esc_attr__( 'Pozadí', 'crdm_basic' ),
Line 76: 'label'     => esc_attr__( 'Bě��ný text', 'crdm_basic' ),
Line 97: 'label'     => esc_attr__( 'Barva odkaz��', 'crdm_basic' ),
INFO: Non-printable characters were found in the Content.php file. You may want to check this file for errors.
Line 41: 'label'     => esc_attr__( 'Pozadí', 'crdm_basic' ),
Line 62: 'label'     => esc_attr__( 'Bě��ný text', 'crdm_basic' ),
Line 83: 'label'     => esc_attr__( 'Barva odkaz��', 'crdm_basic' ),
Line 99: 'description' => esc_attr__( 'Barva bude pou��ita i pro dal��í prvky na stránce (seznamy, tabulky, ...)', 'crdm_basic
INFO: Non-printable characters were found in the ColorVariant.php file. You may want to check this file for errors.
Line 24: 'title' => esc_attr__( 'Barevná varianta', 'crdm_basic' ),
Line 34: 'description' => esc_attr__( 'POZOR! Po ulo��ení budou stávající nastavení ��ablony upraveny.', 'crdm_basic' ),
INFO: Non-printable characters were found in the BorderRadius.php file. You may want to check this file for errors.
Line 24: 'title' => esc_attr__( 'Zaoblení', 'crdm_basic' ),
Line 33: 'label'       => esc_attr__( 'Zaoblení prvků', 'crdm_basic' ),
Line 34: 'description' => esc_attr__( 'Zadejte v��etn�� jednotky, např.: 10px', 'crdm_basic' ),
INFO: Non-printable characters were found in the Background.php file. You may want to check this file for errors.
Line 24: 'title' => esc_attr__( 'Pozadí', 'crdm_basic' ),
Line 33: 'label'    => esc_attr__( 'Pozadí webu', 'crdm_basic' ),
Line 54: 'label'       => esc_attr__( 'Pozadí hlavičky 1', 'crdm_basic' ),
Line 55: 'description' => esc_attr__( 'Za li��tou menu', 'crdm_basic' ),
Line 76: 'label'       => esc_attr__( 'Pozadí hlavičky 2', 'crdm_basic' ),
Line 77: 'description' => esc_attr__( 'V pop��edí li��ty menu', 'crdm_basic' ),
Line 98: 'label'       => esc_attr__( 'Pozadí hlavičky 3', 'crdm_basic' ),
Line 99: 'description' => esc_attr__( 'Pod li��tou menu', 'crdm_basic' ),

**Comment by kalich5** [comment]
https://themes.trac.wordpress.org/ticket/57741

**Comment by davidulus** [comment]
Pro child theme nerelevantní.
