### ISSUE TITLE
Chyby

### ISSUE THREAD

**Issue by kalich5** [skaut/crdm-spolky-zaklad#2]
I have had a quick look a the theme and at this point, it does not comply with the requirements.
Before resubmitting the theme, please read the requirements carefully. We do not always have the number of volunteer reviewers to be able to point out issues that are already listed as requirements.
https://make.wordpress.org/themes/handbook/review/required/
License -did not pass
Declare licenses of any resources included such as fonts or images.
Other issues
No minification of scripts or files unless you provide original files.
Non-design related functionality is not allowed:
Meta boxes may only be used for design related options, not for content like sub titles.
Remove any development files. 
WordPress still supports PHP version 5.2.4, so there must not be any PHP warnings, notices or errors, even if the theme is activated on a server with a low PHP version.
What you can do is add a PHP version check that prevents the theme from being activated.
Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /app/public/wp-content/themes/crdm-basic/functions.php on line 3

**Comment by kalich5** [comment]
více na https://themes.trac.wordpress.org/ticket/57741

**Comment by kalich5** [comment]
INFO: Non-printable characters were found in the functions.php file. You may want to check this file for errors.
Line 18: // if incompatible version of WP / PHP => don´t init
Line 61: $this->showAdminNotice( esc_html__( '��ablona ČRDM - základní vy��aduje verzi WordPress 4.9.6 nebo vy����í!'
Line 67: $this->showAdminNotice( esc_html__( '��ablona ČRDM - základní vy��aduje verzi PHP 7.0 nebo vy����í!', 'crdm-
Line 84: <span class='screen-reader-text'>' . __( 'Zav��ít', 'crdm-basic' ) . '</span>
INFO: Non-printable characters were found in the Sidebar.php file. You may want to check this file for errors.
Line 24: 'title' => esc_attr__( 'Postranní panely', 'crdm-basic' ),
Line 33: 'label'     => esc_attr__( 'Pozadí', 'crdm-basic' ),
Line 54: 'label'     => esc_attr__( 'Barva stínu boxu', 'crdm-basic' ),
Line 92: 'label'     => esc_attr__( 'Bě��ný text', 'crdm-basic' ),
Line 113: 'label'     => esc_attr__( 'Barva odkaz��', 'crdm-basic' ),
INFO: Non-printable characters were found in the PageHeader.php file. You may want to check this file for errors.
Line 24: 'title'       => esc_attr__( 'Hlavi��ka stránek', 'crdm-basic' ),
Line 25: 'description' => esc_attr__( 'Hlavi��ka s obrázkem a nadpisem jednotlivých stránek', 'crdm-basic' ),
Line 35: 'description' => esc_attr__( 'Barva pozadí boxu s textem', 'crdm-basic' ),
Line 57: 'description' => esc_attr__( 'Zadejte v��etn�� jednotky, např.: 50px, 10%, ...', 'crdm-basic' ),
INFO: Non-printable characters were found in the Menu.php file. You may want to check this file for errors.
Line 33: 'label'     => esc_attr__( 'Pozadí lišty', 'crdm-basic' ),
Line 54: 'label'     => esc_attr__( 'Položky menu', 'crdm-basic' ),
Line 81: 'label'     => esc_attr__( 'Barva odd��lova��e položek menu', 'crdm-basic' ),
Line 96: 'label'     => esc_attr__( 'Pozadí vysouvacího menu', 'crdm-basic' ),
Line 117: 'label'     => esc_attr__( 'Položky submenu', 'crdm-basic' ),
Line 139: 'label'     => esc_attr__( 'Barva odd��lova��e položek submenu', 'crdm-basic' ),
INFO: Non-printable characters were found in the Init.php file. You may want to check this file for errors.
Line 30: 'title' => esc_attr__( 'Nastaven�� šablony', 'crdm-basic' )
INFO: Non-printable characters were found in the Helpers.php file. You may want to check this file for errors.
Line 34: <span class='screen-reader-text'>' . __( 'Zav��ít', 'crdm-basic' ) . '</span>
INFO: Non-printable characters were found in the Footer.php file. You may want to check this file for errors.
Line 24: 'title' => esc_attr__( 'Patička', 'crdm-basic' ),
Line 33: 'label'     => esc_attr__( 'Pozadí', 'crdm-basic' ),
Line 76: 'label'     => esc_attr__( 'Bě��ný text', 'crdm-basic' ),
Line 97: 'label'     => esc_attr__( 'Barva odkaz��', 'crdm-basic' ),
INFO: Non-printable characters were found in the Content.php file. You may want to check this file for errors.
Line 41: 'label'     => esc_attr__( 'Pozadí', 'crdm-basic' ),
Line 62: 'label'     => esc_attr__( 'Bě��ný text', 'crdm-basic' ),
Line 83: 'label'     => esc_attr__( 'Barva odkaz��', 'crdm-basic' ),
Line 99: 'description' => esc_attr__( 'Barva bude pou��ita i pro dal��í prvky na stránce (seznamy, tabulky, ...)', 'crdm-basic
INFO: Non-printable characters were found in the ColorVariant.php file. You may want to check this file for errors.
Line 24: 'title' => esc_attr__( 'Barevná varianta', 'crdm-basic' ),
Line 34: 'description' => esc_attr__( 'POZOR! Po ulo��ení budou stávající nastavení ��ablony upraveny.', 'crdm-basic' ),
INFO: Non-printable characters were found in the BorderRadius.php file. You may want to check this file for errors.
Line 24: 'title' => esc_attr__( 'Zaoblení', 'crdm-basic' ),
Line 33: 'label'       => esc_attr__( 'Zaoblení prvků', 'crdm-basic' ),
Line 34: 'description' => esc_attr__( 'Zadejte v��etn�� jednotky, např.: 10px', 'crdm-basic' ),
INFO: Non-printable characters were found in the Background.php file. You may want to check this file for errors.
Line 24: 'title' => esc_attr__( 'Pozadí', 'crdm-basic' ),
Line 33: 'label'    => esc_attr__( 'Pozadí webu', 'crdm-basic' ),
Line 54: 'label'       => esc_attr__( 'Pozadí hlavičky 1', 'crdm-basic' ),
Line 55: 'description' => esc_attr__( 'Za li��tou menu', 'crdm-basic' ),
Line 76: 'label'       => esc_attr__( 'Pozadí hlavičky 2', 'crdm-basic' ),
Line 77: 'description' => esc_attr__( 'V pop��edí li��ty menu', 'crdm-basic' ),
Line 98: 'label'       => esc_attr__( 'Pozadí hlavičky 3', 'crdm-basic' ),
Line 99: 'description' => esc_attr__( 'Pod li��tou menu', 'crdm-basic' ),

**Comment by davidulus** [comment]
Nemělo by to představovat problém.
