### ISSUE TITLE
Odpověď z GitHubu

### ISSUE THREAD

**Issue by kalich5** [skaut/crdm-spolky-zaklad#3]
Evidentně je pořád něco špatně...

https://themes.trac.wordpress.org/ticket/57930#comment:1

**Comment by davidulus** [comment]
Podle všeho se na to ještě nikdo nestihl mrknout. Vidím tam jen aut. pozvánku do programu Trusted authors, ale žádný feedback k šabloně.

**Comment by kalich5** [comment]
Ale tak to by se nám taky hodilo ne...? dostat se tam

**Comment by kalich5** [comment]
a je potřeba mít alespoň jednu šablonu publikovanou, jestli to chápu správně
